version: '3'
services:
  ffdemoapp:
    hostname: ffdemoapp
    image: dtdemos/ffdemoapp:1.0.0
    ports:
      - 80:8080
    environment:
      - DT_CUSTOM_PROP=keptn_project=ff-demo keptn_stage=production keptn_service=ffdemoapp
      - DT_RELEASE_PRODUCT=ld-demo
      - DT_RELEASE_STAGE=production
      - DT_RELEASE_VERSION=1.0.0
      - DT_RELEASE_BUILD_VERSION=1.0.0
      - DT_CLUSTER_ID=demo-ffdemoapp-production
      - BANNER_IMAGE=img/dt-ld.png
      - FEATURE_FLAG_PROVIDER=launchdarkly
      - FEATURE_FLAG_SDK_KEY="$$FEATURE_FLAG_SDK_KEY"
  ffdemoappload:
    hostname: demoappload
    image: dtdemos/casdemoappload:1.0.0
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=80
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always